# Generated by Django 4.2.5 on 2023-09-29 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_user',
            field=models.ForeignKey(blank=True, help_text='выберите id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id User'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='id_user',
            field=models.ForeignKey(blank=True, help_text='выберите id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id User'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Введите имя студента ', max_length=50, null=True, verbose_name='student name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(help_text='Введите группу студента ', on_delete=django.db.models.deletion.CASCADE, to='test_django.group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию студента ', max_length=100, verbose_name='student last name'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='direction',
            field=models.ForeignKey(help_text='Введите название дисциплины ', on_delete=django.db.models.deletion.CASCADE, to='test_django.direction', verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(help_text='Введите имя преподавателя ', max_length=50, verbose_name='tutor name'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию преподавателя ', max_length=100, verbose_name='tutor last name'),
        ),
    ]
