# Generated by Django 4.2.5 on 2023-10-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0002_student_id_user_tutor_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='student',
            field=models.ForeignKey(help_text='Введите имя студента', on_delete=django.db.models.deletion.CASCADE, to='test_django.student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
