# Generated by Django 4.2.5 on 2023-11-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0003_alter_lab_student_alter_student_id_alter_tutor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='name',
            field=models.CharField(help_text='Введите название курса', max_length=20, null=True, verbose_name='group name'),
        ),
    ]
