# Generated by Django 4.2.5 on 2023-11-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0005_alter_lab_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='name',
        ),
    ]
