# Generated by Django 4.2.5 on 2023-09-25 14:45

from django.db import migrations, models
import django.db.models.deletion
import test_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('name', models.CharField(help_text='Введите название направления', max_length=50, primary_key=True, serialize=False, verbose_name='name_direction')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название курса', max_length=20, verbose_name='group name')),
                ('course', test_django.models.IntegerRangeField(help_text='Ввелите номер курса', verbose_name='number course')),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя преподавателя', max_length=50, verbose_name='tutor name')),
                ('last_name', models.CharField(help_text='Введите фамилию преподавателя', max_length=100, verbose_name='tutor last name')),
                ('direction', models.ForeignKey(help_text='Введите название дисциплины', on_delete=django.db.models.deletion.CASCADE, to='test_django.direction', verbose_name='direction')),
            ],
            options={
                'db_table': 'Tutor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя студента', max_length=50, null=True, verbose_name='student name')),
                ('last_name', models.CharField(help_text='Введите фамилию студента', max_length=100, verbose_name='student last name')),
                ('date_birth', models.DateField()),
                ('group', models.ForeignKey(help_text='Введите группу студента', on_delete=django.db.models.deletion.CASCADE, to='test_django.group', verbose_name='group')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', test_django.models.IntegerRangeField(help_text='Введите оценку', verbose_name='mark')),
                ('student', models.ForeignKey(help_text='Введите имя студента', on_delete=django.db.models.deletion.CASCADE, to='test_django.student', verbose_name='Лабы')),
                ('tutor', models.ForeignKey(help_text='Введите имя преподавателя', on_delete=django.db.models.deletion.CASCADE, to='test_django.tutor', verbose_name='tutor')),
            ],
            options={
                'db_table': 'Lab',
            },
        ),
    ]
