# Generated by Django 4.2.5 on 2023-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0004_lab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(help_text='Введите название лабы', max_length=20, null=True, verbose_name='Title'),
        ),
    ]
