# Generated by Django 4.2.5 on 2023-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0005_alter_lab_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='tutor',
        ),
        migrations.AddField(
            model_name='lab',
            name='student',
            field=models.ManyToManyField(to='test_django.student'),
        ),
        migrations.AddField(
            model_name='lab',
            name='tutor',
            field=models.ManyToManyField(to='test_django.tutor'),
        ),
    ]
