# Generated by Django 4.2.5 on 2023-11-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0006_remove_lab_student_remove_lab_tutor_lab_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='tutor',
        ),
        migrations.CreateModel(
            name='Extra_Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ManyToManyField(to='test_django.student')),
                ('tutor', models.ManyToManyField(to='test_django.tutor')),
            ],
            options={
                'db_table': 'Extra_Lessons',
            },
        ),
        migrations.AddField(
            model_name='lab',
            name='student',
            field=models.ForeignKey(default=7, help_text='Введите имя студента', on_delete=django.db.models.deletion.CASCADE, to='test_django.student', verbose_name='student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='tutor',
            field=models.ForeignKey(default=6, help_text='Введите имя преподавателя', on_delete=django.db.models.deletion.CASCADE, to='test_django.tutor', verbose_name='tutor'),
            preserve_default=False,
        ),
    ]
